import { useTheme } from '@mui/material/styles';
import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { asApiPath } from '../../../helpers/app-helpers';
import { FlatCollectionWithoutRelations } from '../../../types/additionalFlatTypes';
import ItemList from '../../common/ItemList';
import { ItemListItemModel } from '../../common/ItemListItem';
import { useVisit } from './../../../helpers/history';
import { decodeBrowsePathComponent, formatBrowsePath } from './helpers/format-browse-path';

const SubCollections = ({
  childCollections,
  path,
}: {
  childCollections: FlatCollectionWithoutRelations[];
  path?: string[];
}) => {
  const DEFAULT_THUMBNAIL_URL = '/bad-harzburg-stiftung-logo.png';
  const { visit } = useVisit();
  const { t } = useTranslation();

  const thumbnailURL = useCallback((collection: FlatCollectionWithoutRelations) => {
    if (!collection.thumbnail) return DEFAULT_THUMBNAIL_URL;

    try {
      new URL(collection.thumbnail);
      return collection.thumbnail;
    } catch {
      return asApiPath(collection.thumbnail);
    }
  }, []);

  const {
    palette: {
      primary: { main: primaryColor },
      secondary: { main: secondaryColor },
    },
  } = useTheme();

  const buildItem = (collection: FlatCollectionWithoutRelations, index: number) => {
    let color = index % 2 === 0 ? primaryColor : secondaryColor;
    if (!collection.publishedAt) {
      color = '#EEEEEE';
    }
    return {
      name: decodeBrowsePathComponent(collection.name),
      // thumbnail URL gets auto-generated by a custom strapi provider, therefore we can't check for the provider like in asUploadPath
      background: thumbnailURL(collection),
      color,
      onClick: () => {
        visit(formatBrowsePath(path, collection.name));
      },
    };
  };
  const items: ItemListItemModel[] = [];

  if (!path) {
    items.push({
      name: t('common.latest-pictures'),
      background: DEFAULT_THUMBNAIL_URL,
      color: secondaryColor,
      onClick: () => {
        visit('/latest');
      },
    });
  }

  childCollections.forEach((collection, i) => items.push(buildItem(collection, i)));

  return <ItemList items={items} />;
};

export default SubCollections;
