name: Build & Deploy CI

on:
  push:
    branches: [main]

jobs:
  build_bp_gallery:
    name: Build & Deploy bp-gallery
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/bp-gallery

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate APIConnector
        run: yarn generate-api
      - name: Build bp-gallery
        run: yarn build
      - name: Deploy build files on the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "projects/bp-gallery/build/"
          strip_components: 3
          target: ${{ secrets.REMOTE_TARGET }}
          rm: true
