name: Lint & Test CI

on: [push]

jobs:
  lint_bp_gallery:
    name: Lint bp-gallery
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/bp-gallery

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install bp-gallery dependencies
        run: yarn install --frozen-lockfile
      - name: Install bp-graphql dependencies
        working-directory: ./projects/bp-graphql
        run: yarn install --frozen-lockfile
      - name: Generate APIConnector
        run: yarn generate-api
      - name: Lint bp-gallery
        run: yarn lint

  test_bp_strapi:
    name: Test bp-strapi
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/bp-strapi

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test bp-strapi
        run: yarn test:ci
